import json
from pathlib import Path

import pytest

from terminals.cli import main


class FakeTmux:
    def __init__(self):
        self.calls = []
        self.sessions = set()
        self.capture_text = "captured scrollback\n"

    def run(self, args, check=True, capture_output=False, text=True):
        self.calls.append(list(args))
        if args[:2] == ["tmux", "new-session"]:
            session = args[args.index("-s") + 1]
            self.sessions.add(session)
        elif args[:2] == ["tmux", "kill-session"]:
            session = args[args.index("-t") + 1]
            self.sessions.discard(session)
        elif args[:2] == ["tmux", "capture-pane"]:
            class Result:
                stdout = self.capture_text
            return Result()

        class Result:
            stdout = ""
        return Result()


def read_json(path: Path):
    return json.loads(path.read_text())


def test_start_creates_metadata_logs_and_tmux_session(tmp_path, monkeypatch, capsys):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)

    exit_code = main(["start", "Gmail watcher refactor", "--cwd", str(tmp_path / "repo")])

    assert exit_code == 0
    task_dirs = list(tmp_path.glob("*/*"))
    assert len(task_dirs) == 1
    metadata = read_json(task_dirs[0] / "metadata.json")
    assert metadata["description"] == "Gmail watcher refactor"
    assert metadata["slug"] == "gmail-watcher-refactor"
    assert metadata["status"] == "running"
    assert metadata["cwd"] == str(tmp_path / "repo")
    assert metadata["tmux_session"].startswith("hermes-task-")
    assert (task_dirs[0] / "session.log").exists()
    assert (task_dirs[0] / "events.jsonl").exists()
    bashrc = (task_dirs[0] / "bashrc").read_text()
    assert bashrc.startswith("# Generated by terminals.\n")
    assert "PROMPT_COMMAND=__terminals_prompt_command" in bashrc
    assert "date -Is" not in bashrc
    assert "date '+%Y-%m-%dT%H:%M:%S%z'" in bashrc
    assert any(call[:2] == ["tmux", "new-session"] for call in fake.calls)
    assert any(call[:2] == ["tmux", "pipe-pane"] for call in fake.calls)
    assert "terminals attach" in capsys.readouterr().out


def test_run_is_synchronous_and_logs_event_before_sending_command(tmp_path, monkeypatch):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    main(["start", "Example task", "--cwd", str(tmp_path)])

    exit_code = main(["run", "latest", "echo hello"])

    assert exit_code == 0
    task_dir = next(tmp_path.glob("*/*"))
    events = [json.loads(line) for line in (task_dir / "events.jsonl").read_text().splitlines()]
    command_events = [e for e in events if e["type"] == "command_sent"]
    assert command_events == [{
        "type": "command_sent",
        "at": command_events[0]["at"],
        "command": "echo hello",
        "synchronous": True,
    }]
    send_index = next(i for i, call in enumerate(fake.calls) if call[:2] == ["tmux", "send-keys"])
    # events.jsonl must already contain the command when tmux send-keys happens.
    assert send_index > 0
    assert fake.calls[send_index][-2:] == ["echo hello", "Enter"]
    assert any(call[:2] == ["tmux", "wait-for"] for call in fake.calls)


def test_finish_captures_scrollback_marks_finished_and_kills_tmux_session(tmp_path, monkeypatch):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    main(["start", "Example task", "--cwd", str(tmp_path)])
    task_dir = next(tmp_path.glob("*/*"))
    metadata_before = read_json(task_dir / "metadata.json")

    exit_code = main(["finish", "latest"])

    assert exit_code == 0
    metadata = read_json(task_dir / "metadata.json")
    assert metadata["status"] == "finished"
    assert metadata["ended_at"] is not None
    assert metadata["final_capture"] == "final-capture.txt"
    assert (task_dir / "final-capture.txt").read_text() == "captured scrollback\n"
    assert ["tmux", "kill-session", "-t", metadata_before["tmux_session"]] in fake.calls


def test_list_outputs_known_tasks_as_json(tmp_path, monkeypatch, capsys):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    main(["start", "Example task", "--cwd", str(tmp_path)])
    capsys.readouterr()

    exit_code = main(["list", "--json"])

    assert exit_code == 0
    tasks = json.loads(capsys.readouterr().out)
    assert len(tasks) == 1
    assert tasks[0]["description"] == "Example task"
