import json
import subprocess
from pathlib import Path
from typing import Any

import pytest

from terminals.cli import main


class FakeTmux:
    def __init__(self):
        self.calls = []
        self.sessions = set()
        self.capture_output = "captured scrollback\n"

    def run(self, cmd, **kwargs):
        self.calls.append(cmd)
        if cmd[0] == "tmux" and cmd[1] == "capture-pane":
            return subprocess.CompletedProcess(cmd, 0, stdout=self.capture_output)
        return subprocess.CompletedProcess(cmd, 0)


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def test_start_creates_metadata_logs_and_tmux_session(tmp_path, monkeypatch, capsys):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    
    exit_code = main(["start", "Gmail watcher refactor", "--cwd", str(tmp_path / "repo")])
    
    assert exit_code == 0
    task_dirs = list(tmp_path.glob("*/*"))
    assert len(task_dirs) == 1
    metadata = read_json(task_dirs[0] / "metadata.json")
    assert metadata["description"] == "Gmail watcher refactor"
    assert metadata["slug"] == "gmail-watcher-refactor"
    assert metadata["status"] == "running"
    assert metadata["cwd"] == str(tmp_path / "repo")
    assert metadata["tmux_session"].startswith("hermes-task-")
    assert (task_dirs[0] / "session.log").exists()
    assert (task_dirs[0] / "events.jsonl").exists()
    bashrc = (task_dirs[0] / "bashrc").read_text()
    assert bashrc.startswith("# Generated by terminals.\n")
    assert "PROMPT_COMMAND=__terminals_prompt_command" in bashrc
    assert "date '+%b %-d %H:%M:%S'" in bashrc
    assert "local cwd=${PWD/#$HOME/~}" in bashrc
    assert "PS1=''" in bashrc
    assert any(call[:2] == ["tmux", "new-session"] for call in fake.calls)
    assert any(call[:2] == ["tmux", "pipe-pane"] for call in fake.calls)
    assert "terminals attach" in capsys.readouterr().out


def test_run_executes_command_and_logs_event(tmp_path, monkeypatch):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    main(["start", "Test task", "--cwd", str(tmp_path / "repo")])
    
    main(["run", "latest", "echo hello"])
    
    task_dirs = list(tmp_path.glob("*/*"))
    assert len(task_dirs) == 1
    events = [json.loads(line) for line in (task_dirs[0] / "events.jsonl").read_text().splitlines()]
    
    event_types = [e["type"] for e in events]
    assert "started" in event_types
    assert "logging_started" in event_types
    # command_completed_wait check removed

    send_index = next(i for i, call in enumerate(fake.calls) if call[:2] == ["tmux", "send-keys"])
    assert send_index > 0
    assert fake.calls[send_index][-2:] == ["echo hello", "Enter"]


def test_finish_captures_scrollback_marks_finished_and_kills_tmux_session(tmp_path, monkeypatch):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    main(["start", "Example task", "--cwd", str(tmp_path)])
    task_dir = next(tmp_path.glob("*/*"))
    metadata_before = read_json(task_dir / "metadata.json")
    
    main(["finish", "latest"])
    
    metadata = read_json(task_dir / "metadata.json")
    assert metadata["status"] == "finished"
    assert metadata["ended_at"] is not None
    assert metadata["final_capture"] == "final-capture.txt"
    assert (task_dir / "final-capture.txt").read_text() == "captured scrollback\n"
    assert ["tmux", "kill-session", "-t", metadata_before["tmux_session"]] in fake.calls


def test_list_outputs_known_tasks_as_json(tmp_path, monkeypatch, capsys):
    fake = FakeTmux()
    monkeypatch.setenv("TERMINALS_ROOT", str(tmp_path))
    monkeypatch.setattr("terminals.cli.subprocess.run", fake.run)
    main(["start", "Example task", "--cwd", str(tmp_path)])
    
    main(["list", "--json"])
    
    # Capture stdout and parse json (ignore everything before the first [)
    full_output = capsys.readouterr().out
    json_start = full_output.find("[")
    output = json.loads(full_output[json_start:])
    assert len(output) >= 1
    assert any(t["description"] == "Example task" for t in output)
