from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any

SCHEMA_VERSION = 1
DEFAULT_ROOT = Path("~/.hermes/task-terminals").expanduser()


def now() -> dt.datetime:
    return dt.datetime.now().astimezone()


def iso_now() -> str:
    return now().isoformat(timespec="seconds")


def root_dir() -> Path:
    return Path(os.environ.get("TERMINALS_ROOT", str(DEFAULT_ROOT))).expanduser()


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "task"


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def append_event(task_dir: Path, event: dict[str, Any]) -> None:
    event = {"at": iso_now(), **event}
    with (task_dir / "events.jsonl").open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(event, sort_keys=True) + "\n")


def iter_metadata() -> list[dict[str, Any]]:
    root = root_dir()
    if not root.exists():
        return []
    tasks: list[dict[str, Any]] = []
    for metadata_path in root.glob("*/*/metadata.json"):
        try:
            metadata = read_json(metadata_path)
        except (OSError, json.JSONDecodeError):
            continue
        metadata["metadata_path"] = str(metadata_path)
        tasks.append(metadata)
    tasks.sort(key=lambda item: item.get("started_at", ""))
    return tasks


def resolve_task(selector: str) -> dict[str, Any]:
    tasks = iter_metadata()
    if not tasks:
        raise SystemExit("No task terminals found")
    if selector == "latest":
        return tasks[-1]

    matches = [
        task for task in tasks
        if selector in {
            task.get("task_id"),
            task.get("slug"),
            task.get("tmux_session"),
        }
    ]
    if len(matches) == 1:
        return matches[0]
    if not matches:
        raise SystemExit(f"No task terminal matches {selector!r}")
    raise SystemExit(f"Ambiguous task selector {selector!r}")


def make_bashrc(path: Path) -> None:
    path.write_text(
        "# Generated by terminals.\n"
        "__terminals_prompt_command() {\n"
        "  local status=$?\n"
        "  printf '\\n[terminals] %s exit=%s cwd=%q\\n' \"$(date '+%Y-%m-%dT%H:%M:%S%z')\" \"$status\" \"$PWD\"\n"
        "}\n"
        "PROMPT_COMMAND=__terminals_prompt_command\n"
        "PS1='\\u@\\h:\\w\\$ '\n",
        encoding="utf-8",
    )


def command_start(args: argparse.Namespace) -> int:
    start = now()
    slug = args.slug or slugify(args.description)
    timestamp = start.strftime("%Y%m%d-%H%M%S")
    task_id = f"{timestamp}-{slug}"
    session = f"hermes-task-{task_id}"
    task_dir = root_dir() / start.strftime("%Y-%m-%d") / task_id
    task_dir.mkdir(parents=True, exist_ok=False)
    cwd = str(Path(args.cwd).expanduser())
    Path(cwd).mkdir(parents=True, exist_ok=True)

    (task_dir / "session.log").touch()
    (task_dir / "events.jsonl").touch()
    bashrc = task_dir / "bashrc"
    make_bashrc(bashrc)

    metadata = {
        "schema_version": SCHEMA_VERSION,
        "task_id": task_id,
        "slug": slug,
        "description": args.description,
        "tmux_session": session,
        "tmux_window": 0,
        "tmux_pane": 0,
        "cwd": cwd,
        "log_dir": str(task_dir),
        "session_log": "session.log",
        "events_log": "events.jsonl",
        "final_capture": None,
        "started_at": start.isoformat(timespec="seconds"),
        "ended_at": None,
        "status": "running",
    }
    write_json(task_dir / "metadata.json", metadata)
    append_event(task_dir, {"type": "started", "description": args.description})

    shell_command = f"bash --rcfile {shlex.quote(str(bashrc))} -i"
    subprocess.run([
        "tmux", "new-session", "-d", "-s", session, "-c", cwd, shell_command,
    ], check=True)
    subprocess.run(["tmux", "set-option", "-t", session, "history-limit", str(args.history_limit)], check=True)
    subprocess.run([
        "tmux", "pipe-pane", "-o", "-t", session,
        f"tee -a {shlex.quote(str(task_dir / 'session.log'))}",
    ], check=True)
    append_event(task_dir, {"type": "logging_started"})

    print(f"Started task terminal: {task_id}")
    print(f"tmux session: {session}")
    print(f"attach: terminals attach {task_id}")
    print(f"direct: tmux attach -t {session}")
    print(f"logs: {task_dir}")
    return 0


def command_run(args: argparse.Namespace) -> int:
    task = resolve_task(args.task)
    task_dir = Path(task["log_dir"])
    command = args.command
    append_event(task_dir, {"type": "command_sent", "command": command, "synchronous": True})
    channel = f"terminals-{task['task_id']}-{now().strftime('%H%M%S%f')}"
    session = task["tmux_session"]
    subprocess.run(["tmux", "send-keys", "-t", session, command, "Enter"], check=True)
    subprocess.run(["tmux", "send-keys", "-t", session, f"tmux wait-for -S {shlex.quote(channel)}", "Enter"], check=True)
    subprocess.run(["tmux", "wait-for", channel], check=True)
    append_event(task_dir, {"type": "command_completed_wait", "command": command})
    return 0


def command_attach(args: argparse.Namespace) -> int:
    task = resolve_task(args.task)
    os.execvp("tmux", ["tmux", "attach", "-t", task["tmux_session"]])
    return 0


def command_finish(args: argparse.Namespace) -> int:
    task = resolve_task(args.task)
    task_dir = Path(task["log_dir"])
    session = task["tmux_session"]
    result = subprocess.run(["tmux", "capture-pane", "-t", session, "-p", "-S", "-"], check=True, capture_output=True, text=True)
    (task_dir / "final-capture.txt").write_text(result.stdout, encoding="utf-8")
    task["status"] = "finished"
    task["ended_at"] = iso_now()
    task["final_capture"] = "final-capture.txt"
    task.pop("metadata_path", None)
    write_json(task_dir / "metadata.json", task)
    append_event(task_dir, {"type": "finished"})
    subprocess.run(["tmux", "kill-session", "-t", session], check=True)
    print(f"Finished task terminal: {task['task_id']}")
    print(f"capture: {task_dir / 'final-capture.txt'}")
    return 0


def command_list(args: argparse.Namespace) -> int:
    tasks = iter_metadata()
    for task in tasks:
        task.pop("metadata_path", None)
    if args.json:
        print(json.dumps(tasks, indent=2, sort_keys=True))
    else:
        for task in tasks:
            print(f"{task['task_id']}\t{task['status']}\t{task['description']}")
    return 0


def command_archive(args: argparse.Namespace) -> int:
    tasks = [t for t in iter_metadata() if t.get("status") == "finished"]
    if args.query:
        tasks = [t for t in tasks if args.query.lower() in t.get("description", "").lower()]

    total = len(tasks)
    to_display = tasks[-10:][::-1]

    print(f"Showing {len(to_display)} of {total} finished tasks:")
    for task in to_display:
        print(f"{task['task_id']}\t{task['description']}")

    if total > 10:
        print(f"... and {total - 10} more. Use a query to search.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="terminals")
    subparsers = parser.add_subparsers(dest="command", required=True)

    start = subparsers.add_parser("start", help="start a logged task terminal")
    start.add_argument("description")
    start.add_argument("--cwd", default=os.getcwd())
    start.add_argument("--slug")
    start.add_argument("--history-limit", type=int, default=200000)
    start.set_defaults(func=command_start)

    run = subparsers.add_parser("run", help="run a command synchronously in a task terminal")
    run.add_argument("task")
    run.add_argument("command")
    run.set_defaults(func=command_run)

    attach = subparsers.add_parser("attach", help="attach to a task terminal")
    attach.add_argument("task", nargs="?", default="latest")
    attach.set_defaults(func=command_attach)

    finish = subparsers.add_parser("finish", help="capture and close a task terminal")
    finish.add_argument("task", nargs="?", default="latest")
    finish.set_defaults(func=command_finish)

    list_cmd = subparsers.add_parser("list", help="list task terminals")
    list_cmd.add_argument("--json", action="store_true")
    list_cmd.set_defaults(func=command_list)

    archive = subparsers.add_parser("archive", help="list and search archived task terminals")
    archive.add_argument("query", nargs="?", help="optional search term")
    archive.set_defaults(func=command_archive)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


def entrypoint() -> None:
    raise SystemExit(main())


if __name__ == "__main__":
    entrypoint()
